# Generated by Django 5.2.10 on 2026-03-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('owner', models.IntegerField(blank=True, null=True)),
                ('is_hq', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=2)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='maps.map')),
            ],
        ),
        migrations.CreateModel(
            name='MapUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('type', models.CharField(max_length=2)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_units', to='maps.map')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_units', to='maps.tile')),
            ],
        ),
    ]
