# Generated by Django 5.2.10 on 2026-03-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('type', models.CharField(choices=[('G', 'Grass'), ('S', 'Sea'), ('F', 'Forest'), ('M', 'Mountain'), ('V', 'River'), ('R', 'Road'), ('B', 'Bridge')], max_length=1)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='games.map')),
            ],
        ),
    ]
