# Generated by Django 5.2.10 on 2026-03-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.map')),
            ],
        ),
    ]
