# Generated by Django 5.2.10 on 2026-03-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='initial_owner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='type',
            field=models.CharField(choices=[('GR', 'Grass'), ('SE', 'Sea'), ('BE', 'Beach'), ('FR', 'Forest'), ('MT', 'Mountain'), ('RV', 'River'), ('RO', 'Road'), ('BR', 'Bridge'), ('CT', 'City'), ('FC', 'Factory'), ('PO', 'Port'), ('AP', 'Airport'), ('HQ', 'Headquarters')], max_length=2),
        ),
    ]
